str = raw_input("Enter your input: ")
shiv =raw_input("What is your name: ")
str1 =raw_input("What is your Father's name: ")
print("My Father's name is:",str1)
print("My name is: ",shiv)
print ("Received input is : ", str)